### ISSUE TITLE
Access to the baseline solution weights

### ISSUE THREAD

**Issue by eistakovskii** [dialogue-evaluation/RuCoCo-2023#3]
Hi! Is it possible to get access to the pretrained weights linked [here](https://github.com/dialogue-evaluation/RuCoCo-2023/tree/main/baseline) or are they intended to be shared only with the RoCoCo-2023 participants?

**Comment by vdobrovolskii** [comment]
Hi!
The link should be available to everyone now, thanks for noticing!
