### ISSUE TITLE
Both training and inference crash on Kaggle

### ISSUE THREAD

**Issue by eistakovskii** [dialogue-evaluation/RuCoCo-2023#4]
If you are using Kaggle to train the baseline solution right of the box with the GPU accelerator on and the --max_batches_train set to 1 in the train.py arguments, the training process crashes with the following error message
![image](https://user-images.githubusercontent.com/104836394/216315393-afda9b29-a752-45e6-b438-fa69937d7270.png)

**Comment by vdobrovolskii** [comment]
Kaggle is using Python 3.7, while the repository has only been tested with Python 3.9.

The following should work (as of 02.02.23):

Relax the version constraints in `requirements.txt`:
```
pytorch-lightning
spacy
torch
transformers
```
